version: '3.7'
services:

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./v1.0.0:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MyDatabase

  admin:
    image: adminer
    ports:
      - 8081:8080

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin
