version: '2.4' # last version that supports depends_on / condition...
 
services:

  mssql:
    image: microsoft/mssql-server-linux:latest
    ports:
      - 1433:1433
    volumes:
      - ./mssql/v1.0.0:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@55w0rd
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@55w0rd -d MyDatabase -Q 'SELECT 1 FROM MyDatabase'
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  integration:
    image: webapi-integration-tests:0.0.1
    build:
      context: .
      dockerfile: ./src/IntegrationTests/Dockerfile.Integration
    volumes:
      - ./src/WebApi/appsettings.Integration.json:/home/app/WebApi/appsettings.Development.json
    depends_on:
      mssql:
        condition: service_healthy